"""create tariffs and payments

Revision ID: a333a17d3055
Revises:
Create Date: 2026-10-08 17:54:44.452238

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a333a17d3055"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tariffs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariffs")),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "succeeded",
                "failed",
                "refunded",
                name="paymentstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("tariff_id", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("discount", sa.BigInteger(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "card", "sbp", "installment", name="paymentmethod", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("installment_months", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(method = 'installment') = (installment_months IS NOT NULL)",
            name=op.f("ck_payments_installment_months_matches_method"),
        ),
        sa.CheckConstraint(
            "method IN ('card', 'sbp', 'installment')", name=op.f("ck_payments_method_allowed")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'succeeded', 'failed', 'refunded')",
            name=op.f("ck_payments_status_allowed"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.CheckConstraint("discount >= 0", name=op.f("ck_payments_discount_non_negative")),
        sa.CheckConstraint(
            "installment_months IS NULL OR installment_months IN (3, 6, 12)",
            name=op.f("ck_payments_installment_months_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["tariff_id"], ["tariffs.id"], name=op.f("fk_payments_tariff_id_tariffs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_payments_idempotency_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_table("tariffs")
    # ### end Alembic commands ###
